dfa/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.graphs, name='graphs'),
    re_path('get_data/(?P<graph_type>.+)/$', views.get_data, name='get_data'),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('dfa.urls', 'dfa'), namespace='dfa')),
]

dfa/models.py
import math
import numpy as np

from .data import nile_minima_data

from .calculate_numpyless import calculate_not_using_numpy


def get_possible_data_length(data):
    """
    Gets the maximum possible length of data with the length of 2^n from
    the given original data list.

    Args:
        data (list): A given original data list.

    Returns:
        The list maximum possible numbers of 2^n to obtain from given list,
        where n is natural number.
    """
    possible_data_length = []
    data_length = len(data)
    for i in range(1, round(math.log2(data_length)) + 1):
        number = 2**i
        if number <= data_length:
            possible_data_length.append(number)
        else:
            break
    return possible_data_length


def get_possible_segments_length(possible_data_length):
    """
    Calculates the dictionary with the elements of possible_data_length as
    keys and its possible combinations of power of 2 as values.

    Args:
        possible_data_length (list): A list of possible data length to
        obtain from a list of an original data list.

    Returns:
        The dictionary of a given list.
        e.g.: {2: [2], 4: [2, 4], 8: [2, 4, 8], ...}.
    """
    possible_segments = {}
    for number in possible_data_length:
        possible_segments[number] = [
            2**i for i in range(1, round(math.log2(number)) + 1)
        ]
    return possible_segments


def filter_given_values_out_from(json_data, given_key):
    """
    Filters out only values with keys "level" from sample data json
    and stores them in a new list.

    Args:
        json_data (list): A list of dictionaries.
        given_key (str): A string determining the key type.

    Returns:
        The new list storing the values of levels.
    """
    return [value
            for dictionary in json_data
            for key, value in dictionary.items()
            if key == given_key]


def calculate_y(x, a, b):
    """
    Calculates the linear regressions Y[n]'s value for given X[n], a and b,
    where n is a natural number.

    Args:
        x (list): A list of X[n].
        a (float): A float number a.
        b (float): A float number b.

    Returns:
        A list of calculated Y[n].
    """
    return [a*x[i] + b for i in range(len(x))]


def split_list_into_segments(data_list, number_to_split):
    """
    Splits/Divides the original data list into N number of sub lists.

    Args:
        data_list (list): A list of original data.
        number_to_split (int): A number to split original data in.

    Returns:
        The list of N number split lists into segments.
    """
    count = 0
    each_segment = []
    segments_list = []

    for i in range(len(data_list)):
        each_segment.append(data_list[i])
        count += 1
        if count > 0 and count % number_to_split == 0:
            count = 1
            segments_list.append(each_segment)
            each_segment = [data_list[i]]
    return segments_list


def calculate_each_segments_f_l(segments_length, a, b, y):
    sum_of_y = 0
    for i in range(len(y)):
        sum_of_y += np.power((y[i] - a*i - b), 2)
    return np.sqrt(np.multiply((1/segments_length), sum_of_y))


def calculate_average_f_l(f_l_list):
    average_f_l = np.mean(f_l_list)
    return average_f_l


def get_classic_dfa_data(data_length, segments_length):
    # Stores the each segments data.
    calculated_data = []
    # Stores the calculated F(L) of each segments.
    f_l_list = []
    # Stores the formula y = a*x + b of each segments.
    formula_list = []
    # Taking the first N-th element and creating
    # a new list which is exponent of 2.
    sample_data = nile_minima_data[:(data_length + 1)]

    segments_number = round(data_length / segments_length)

    # Filtering levels out from sample data and storing them to a new list.
    x = filter_given_values_out_from(sample_data, 'year')
    y = filter_given_values_out_from(sample_data, 'level')

    segments_x = split_list_into_segments(x, segments_length + 1)
    segments_y = split_list_into_segments(y, segments_length + 1)

    # Getting the minimum and the maximum value of X series.
    min_x = np.min(x)
    max_x = np.max(x)

    # Getting the minimum and the maximum value of Y series.
    min_y = np.min(y)
    max_y = np.max(y)

    # Dividing the original series into segments.
    for i in range(segments_number):
        # First step: Calculating the average of Xn and Yn series.
        x_average = np.mean(segments_x[i])
        y_average = np.mean(segments_y[i])

        # Second step: Converting the series to a "Random Walk".
        # i.e.: Calculating the cumulative sums.
        x_cumulative_sum = np.cumsum(segments_x[i] - x_average)
        y_cumulative_sum = np.cumsum(segments_y[i] - y_average)

        # Third step: Dividing the series into segments of length L and
        # fitting a straight line within each segment.
        # a = x_cumulative_sum / y_cumulative_sum
        a = np.divide(
            np.sum(y_cumulative_sum),
            np.sum(x_cumulative_sum)
        )

        # b = y - a*x
        b = np.subtract(y_average, np.multiply(a, x_average))

        new_y = calculate_y(segments_x[i], a, b)

        # Fourth step: Calculating F(L) for each segments.
        f_l = calculate_each_segments_f_l(segments_length, a, b, new_y)
        f_l_list.append(f_l)

        # Saving each segment's formulas.
        formula_text = "{}. Y = {}*X + {} <strong>F(L) = {}</strong>"\
            .format(i + 1, a, b, f_l)

        for j in range(len(new_y)):
            segments_data = {
                'year' + str(i): segments_x[i][j],
                'level' + str(i): new_y[j]
            }
            calculated_data.append(segments_data)

            formula_text += "<br>&emsp;&emsp;Y[{}] = {}, X[{}] = {}"\
                .format(j + 1, new_y[j], j + 1, segments_x[i][j])

        formula_list.append(formula_text)

    # Fifth step: Calculating the average F^(L)
    # over all segments of the same length.
    f_l_average = calculate_average_f_l(f_l_list)

    # Sixth step: Calculating the alpha (Hurst Exponent).
    alpha = math.log(f_l_average, segments_length)

    return {
        'sample_data': sample_data,
        'calculated_data': calculated_data,
        'data_length': data_length,
        'segments_length': segments_length,
        'segments_number': segments_number,
        'formula_list': formula_list,
        'f_l_list': f_l_list,
        'f_l_average': f_l_average,
        'alpha': alpha,
        'min_x': int(min_x),
        'max_x': int(max_x),
        'min_y': min_y,
        'max_y': max_y
    }


def get_modified_dfa_data(segments_length):
    # Taking the first N-th element and creating
    # a new list which is exponent of 2.
    sample_data = nile_minima_data[:32]
    # print("\n In get modified dfa data method!")
    return {'data': sample_data}

dfa/views.py
import json

from django.http.response import HttpResponse
from django.shortcuts import render

from .config import graph_styles, \
    default_data_length, \
    default_segments_length
from .data import nile_minima_data
from . import models


def graphs(request):
    possible_data_length = models.get_possible_data_length(nile_minima_data)

    possible_segments_length = \
        models.get_possible_segments_length(possible_data_length)

    context = {
        'view': 'graphs',
        'graph_type': 'classic_dfa',
        'graph_styles': graph_styles,
        'default_data_length': default_data_length,
        'default_segments_length': default_segments_length,
        'possible_data_length': possible_data_length,
        'possible_segments_length': json.dumps(possible_segments_length),
    }
    return render(request, 'dfa/graphs.html', context)


def get_data(request, graph_type):
    data = {}

    data_length = default_data_length
    segments_length = default_segments_length

    url_query = {}
    for key in request.GET.keys():
        url_query[key] = request.GET.getlist(key)
        if key == 'data_length':
            data_length = int(url_query.pop('data_length', [None])[0])
        if key == 'segments_length':
            segments_length = int(url_query.pop('segments_length', [None])[0])

    # print("graph_type = {}, data_length = {}, segments_length = {}"
    #       .format(graph_type, data_length, segments_length))
    if graph_type == 'classic_dfa':
        data = models.get_classic_dfa_data(data_length, segments_length)
    return HttpResponse(json.dumps(data))

dfa/templates/dfa/base.html
{% load staticfiles %}
{% load tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Detrended Fluctuation Analysis</title>
        <!-- Importing jquery and jquery min javascript files! -->
        <script type="text/javascript" src="{% static 'dfa/jquery/jquery.min.js' %}"></script>
        <!-- -->
        <script type="text/javascript" src="{% static 'dfa/amcharts/core.js' %}"></script>
        <script type="text/javascript" src="{% static 'dfa/amcharts/charts.js' %}"></script>
        <script type="text/javascript" src="{% static 'dfa/amcharts/animated.js' %}"></script>
        <script type="text/javascript" src="{% static 'dfa/graphs.js' %}"></script>
        <!-- Importing bootstrap and custom css files! -->
        <link rel="stylesheet" href="{% static 'dfa/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'dfa/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/dfa.css' %}">
        <link rel="stylesheet" href="{% static 'css/graphs.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Detrended Fluctuation Analysis</h1>
            </div>

            <div class="top-nav">
                <a href="/">Home</a>
                <a href="/" style="float:right">Login</a>
            </div>

            <div class="content">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </body>
</html>

dfa/templates/dfa/graphs.html
{% extends 'dfa/base.html' %}

{% load staticfiles %}
{% load tags %}

{% block content %}
    <div class="graph-container">
        <div class="form-inline" style="padding-top:20px; padding-left:20px;">
            <!-- The select option "possible_data_length_select" which controls the other select! -->
            <div class="form-group mx-sm-3 mb-2">
                <label for="possible_data_length_select">Data length in years:</label>
                <select class="form-control" id="possible_data_length_select" required="required">
                    <option value="">Select years</option>
                    {% for data_length in possible_data_length %}
                        <option value="{{ data_length }}" {% if data_length == default_data_length %} selected="selected" {% endif %}>{{ data_length }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- The dynamic select options, which is dependent from the selection made on select option "possible_data_length_select"! -->
            <div class="form-group mx-sm-3 mb-2">
                <label for="possible_segments_length_select">The segments length L:</label>
                <select class="form-control" id="possible_segments_length_select" required="required">


                </select>
            </div>
            <button type="submit" id="calculate_button" class="btn btn-primary mb-2">Calculate!</button>
        </div>

        <div class="card card-primary">
            <div class="card-heading">
                <div class="card-title" style="margin: auto auto;">
                    <span class="pull-right"><button type="button" class="btn btn-default btn-xs" onclick="getDataThenBuildGraph('{{ graph_type }}');"><span class="fa fa-refresh"></span></button></span>
                    {{  graph_styles|get_value_by_key:graph_type|get_value_by_key:'name' }}
                </div>

            </div>
        </div>

        <div class="card-body">
            <div id="classic_dfa" style="height: 600px;">

            </div>
        </div>
    </div>

    <div id="calculated_data_container" class="container">
        <div class="card-body">

        </div>
    </div>

    {% block script %}
        <script type="text/javascript">
            var default_data_length = '';
            var default_segments_length = '';
            var options = '';
            var possible_segments_length = '';

            $(document).ready(function() {
                urls['{{ graph_type }}'] = '{% url 'dfa:get_data' graph_type %}';
                getDataThenBuildGraph('{{ graph_type }}');

                default_data_length = '{{ default_data_length }}';
                default_segments_length = '{{ default_segments_length }}';
                // Dynamic "possible_segments_length_select" select option.
                options = "<option value=''>Select segments</option>";
                possible_segments_length = {{ possible_segments_length|safe }};

                // Initializing the starting values of select option "possible_segments_length".
                if (possible_segments_length.hasOwnProperty(default_data_length)) {
                    var default_segments_list = possible_segments_length[default_data_length];
                    for (var i = 0; i < default_segments_list.length; ++i) {
                        if (default_segments_list[i] === parseInt(default_segments_length)){
                            options += "<option value=" + default_segments_list[i] + " selected='selected'>" + default_segments_list[i] + "</option>";
                        } else {
                            options += "<option value=" + default_segments_list[i] + ">" + default_segments_list[i] + "</option>";
                        }
                    }
                    $('#possible_segments_length_select').html(options);
                } else {
                    $('#possible_segments_length_select').find('option').remove();
                }

                // Every time when the value of select option "possible_data_length" changes!
                $('#possible_data_length_select').on('change', function() {
                    // Getting the selected value.
                    var selected_value = $(this).val();
                    // Setting the default option's value.
                    options = "<option value=''>Select segments</option>";
                    // Checking if the possible_segments_length has a key with same value as selected value.
                    if (possible_segments_length.hasOwnProperty(selected_value)){
                        var segments_list = possible_segments_length[selected_value];
                        for (var i = 0;  i < segments_list.length; ++i){
                            if (segments_list[i] === parseInt(selected_value)) {
                                options += "<option value=" + segments_list[i] + " selected='selected'>" + segments_list[i] + "</option>";
                            } else {
                                options += "<option value=" + segments_list[i] + ">" + segments_list[i] + "</option>";
                            }
                        }
                        $('#possible_segments_length_select').html(options);
                    } else {
                        $('#possible_segments_length_select').find('option').remove();
                    }
                });

                $('#calculate_button').click(function start_custom_calculation(){
                    var data_length = $('#possible_data_length_select option:selected').text();
                    var segments_length = $('#possible_segments_length_select option:selected').text();

                    var data_to_send = "data_length=" + data_length + "&segments_length=" + segments_length;

                    $.get("{% url 'dfa:get_data' graph_type %}", data_to_send, function(data){
                        var json_data = JSON.parse(data);
                        buildAmCharts4Graphs(json_data, '{{ graph_type }}');
                    });
                });
            });
        </script>
    {% endblock %}
{% endblock %}